---
# +-----Title------------------------------------------------------------------+
title: "From gene expression to pathway and transcription factor activities to study chronic liver diseases"

# +-----Author-----------------------------------------------------------------+
author: "Christian H. Holland"
date: "`r Sys.Date()`"
degree: "M.Sc."
birthplace: "Jülich, Germany"

# +-----Supervisors------------------------------------------------------------+
advisor: "Prof. Dr. Ursula Klingmüller"
altadvisor: "Prof. Dr. Julio Saez-Rodriguez"

# +-----Dates------------------------------------------------------------+
submissionmonth: "September"
submissionyear: "2021"
defense: "03.12.2021"

knit: bookdown::render_book
site: bookdown::bookdown_site

header-includes:
  - \usepackage[parfill]{parskip}
  - \usepackage{tocloft}

# This will automatically install the {remotes} package and {thesisdown}
# Change this to FALSE if you'd like to install them manually on your own.
params:
  'Install needed packages for {thesisdown}': True
  
# Remove the hashtag to specify which version of output you would like.
# Can only choose one at a time.
output:
  # thesisdown::thesis_pdf:
  #     toc_depth: 2
  #     extra_dependencies: ["flafter"]
  thesisdown::thesis_gitbook: default
 # thesisdown::thesis_word: default
 # thesisdown::thesis_epub: default

# If you are creating a PDF you'll need to write your preliminary content 
# (e.g., abstract, acknowledgements) below or use code similar to line 25-26 
# for the .RMD files. If you are NOT producing a PDF, delete or silence
# lines 25-39 in this YAML header.
abstract: '`r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "abstract.Rmd")), collapse = "\n  ")`'
zusammenfassung: '`r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "zusammenfassung.Rmd")), collapse = "\n  ")`'
# preface: |
#   This is an example of a thesis setup to use the reed thesis document class 
#   (for LaTeX) and the R bookdown package, in general.
# Specify the location of the bibliography below
bibliography: bib/references.bib
# Download your specific csl file and refer to it in the line below.
csl: style/apa.csl
lot: false
lof: false
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of 
metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete the section entirely, or silence them (add # before each line). 

If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.

If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r knitr-config, include=FALSE}
knitr::opts_chunk$set(
  echo      = FALSE,
  warning   = FALSE,
  message   = FALSE,
  error     = FALSE,
  cache     = FALSE,
  fig.ext   = "png",
  fig.path  = "figures/",
  fig.align = "center",
  out.width = "80%",
  # fig.pos = "!H", 
  # out.extra = "",
  dev = "png",
  dpi = 300
)
```

```{r include-packages, include=FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if (!require(remotes)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("remotes", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste('You need to run install.packages("remotes")",
            "first in the Console.')
    )
  }
}
if (!require(thesisdown)) {
  if (params$`Install needed packages for {thesisdown}`) {
    remotes::install_github("ismayc/thesisdown")
  } else {
    stop(
      paste(
        "You need to run",
        'remotes::install_github("ismayc/thesisdown")',
        "first in the Console."
      )
    )
  }
}
library(thesisdown)
# Set how wide the R output will go
options(width = 70)
```

```{r libraries}
# File paths
library(here)

# Plotting
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(maps)
library(AachenColorPalette) # devtools::install_github("christianholland/AachenColorPalette")
library(tidygraph)
library(ggraph)
library(ggrepel)
library(scales)
# library(magick)
library(cowplot)

theme_set(theme_cowplot())

# Strings
library(stringr)

# File IO
library(readr)
library(bib2df)

# Presentation
library(knitr)

# Manipulation
library(dplyr)
library(tidyr)
library(purrr)
library(forcats)

# Tables
library(tibble)
library(kableExtra)

# Dates
library(lubridate)

# APIs
library(scholar)
# library(googleAnalyticsR)

```

```{r functions}
my_today = function() {
  format(Sys.time(), '%d %B %Y')
}
```

`r if(!knitr:::is_latex_output()) '# Front matter {-}'`

## Preface {-}
```{r child=here::here("prelims", "preface.Rmd")}

```

## Acknowledgements {-}
```{r child=here::here("prelims", "acknowledgements.Rmd")}

```

`r if(!knitr:::is_latex_output()) '## Abstract {-}'`
```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "abstract.Rmd")}

```

<!-- `r if(!knitr:::is_latex_output()) '## Zusmmenfassung {-}'` -->
<!-- ```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "zusammenfassung.Rmd")} -->

<!-- ``` -->

<!-- The {.unnumbered} option here means that the introduction will be 
"Chapter 0." You can also use {-} for no numbers on chapters.
-->
